<a href="https://colab.research.google.com/github/Birawin/Data-Science-with-Python-/blob/main/MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Relevant Data & Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [3]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [5]:
data.tail()

price     size  year
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

In [4]:
data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

Based on our analysis of the data above, it is evident that the independent variables in this case are the year (to be determined whether this has an influence on the variance between the home prices) & size of the homes. The dependent variable is the price of the home.

In [7]:
#Declare Independent & Dependent Variables

x = data[['size','year']]
y = data['price']

In [10]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [12]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [13]:
reg.intercept_

-5772267.017463279

In [14]:
#R-Squared

reg.score(x,y)

0.7764803683276795

In [15]:
#Adjusted R-Squared
def adj_r2(x,y):
  r2 = reg.score(x,y)
  n = x.shape[0]
  p = x.shape[1]
  adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
  return adjusted_r2


In [16]:
adj_r2(x,y)

0.7718717161282502

In [17]:
reg.predict([[750,2009]]) #Finding the Predicted Price of an Apartment that has a size of 750 sq.ft. from 2009

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([258330.34465995])

In [18]:
from sklearn.feature_selection import f_regression

In [19]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [22]:
p_values = f_regression(x,y)[1]
p_values.round(6)

#Size values are useful in explaining the regression in our model (P <= 0.005).

array([0.      , 0.357341])

In [24]:
reg_summary = pd.DataFrame(data=['size', 'year'], columns =['Features'])

In [25]:
reg_summary

Features
0     size
1     year

In [26]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['P-Value'] = p_values.round(3)

In [27]:
reg_summary

Features  Coefficients  P-Value
0     size    227.700854    0.000
1     year   2916.785327    0.357