<a href="https://colab.research.google.com/github/Birawin/Data-Science-with-Python-/blob/main/sklearn_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Import the Relevant Data

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [9]:
# Load the Data
data = pd.read_csv('1.02.+Multiple+linear+regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [10]:
data.describe()

#Rand 1,2,3 - randomly assigns 1, 2, 3

#Sample - The Machine Learning Word for Observations

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [11]:
# Create The Multiple Linear Regression

#Declare the Dependent & Independent Variables
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [12]:
# Regression itself

reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [13]:
#Coefficient
reg.coef_

#Coefficient of SAT and RAND 1,2,3

array([ 0.00165354, -0.00826982])

In [14]:
#Intercept

# y = mx + b (b = intercept, m = coefficent)

reg.intercept_

0.29603261264909486

In [15]:
#Calculating the R-Squared

#R-squared - a universal measure to evaluate how well linear regressions fare and compare...

reg.score(x,y) #Varies depending on the type of regression you're performing


0.4066811952814283

In [16]:
#Adjusted R-Squared Steps on the R-squared and adjusts for the number of variables included in the model

reg.score(x,y)

0.4066811952814283

###**Formula for Adjusted R^2**
$R^2_(adj.) = 1 - (1-R^2)* ((n-1)/(n-p-1))$

In [17]:
x.shape


(84, 2)

In [18]:
n = x.shape[0]
p = x.shape[1]

In [19]:
r2 = reg.score(x,y)

In [20]:
r2 = reg.score(x,y)

In [21]:
adjusted_r2 = 1 - (1-r2)*((n-1)/(n-p-1))
adjusted_r2

0.3920313482513401

#The Adjusted R^2 Value shows that one of the two variables does not increase the explanatory power of the regression. (Since it is less than the R^2 value)
#If we could identify which one and remove it, then we could further simplify our model.
# In order to detect the variables which are unneeded in a model, we will have to execute the 'Feature Selection Process'.


In [23]:
# Feature Selection (Simplifies Model, Improves speeds and prevents a series of unwanted issues arising from having too many features)

In [ ]:
#F-regression creates simple linear regressions of each feature & the dependent variable

In [24]:
#1. GPA <- SAT
#2 GPA <- RAND 1,2,3

#Creates P-values for each regression - p Value is a number, calculated from a statistical test, that describes how likely you are to have found a particular set of observations if the null hypothesis were true.

In [22]:
from sklearn.feature_selection import f_regression

In [25]:
p_values = f_regression(x,y)[1]

In [26]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [27]:
p_values.round()

# SAT - p-value = 0.000
#RAND 1,2,3 - p-value = 1


#Note: These are the univariate p-values reached from simple linear models.
#Tehy do not reflect the interconnection of the features in our multiple linear regression

array([0., 1.])

**#From the calculation above, SAT scores are useful in explaining the regression in our model (P <= 0.005).**

In [28]:
#Creating A Summary Table

reg_summary = pd.DataFrame(data=['SAT', 'Rand 1,2,3'], columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [29]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [30]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

### Standardization

In [31]:
# StandardScaler() - This preprocessing module from sci-kit leaarn is used to standardized data

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()

In [34]:
scaler.fit(x)

StandardScaler()

In [37]:
x_scaled = scaler.transform(x) # Transforms the unscaled inputs using the information contained in the scaler object (feature-wise)

In [38]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [41]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [42]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [43]:
reg.intercept_

3.330238095238095

**Creating a Summary Table**

In [48]:
reg_summary = pd.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [50]:
reg_summary

#Rand 1,2,3 - barely contributes to our model. When we perform feature scaling, we don't care if a useless variable is there or not.

Features   Weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

SAT is ranging between 600 & 2400, while Rand 1,2,3 between 1 and 3...

Feature Scaling - Having all inputs with the same magnitude allows us to compare their impact.

Whenever we get new data, we scale the data like this:

new_data = pd.read_csv('new_data.csv')
scaler #contains all standardization info

new_data_scaled = scaler.transform(new_data)

Making Predictions with the Standardized Coefficients (Weights)


In [65]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns =['SAT', 'Rand 1,2,3'])

In [66]:
reg.predict(new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

The results above does not fit the standard criteria of a GPA value. This because the model expects value that are of the same magnitude - now that the input data consists of standardized data

The new data frame should be arranged in the same way. It must be standardized in the same way.

In [67]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [68]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [ ]:
## What if we removed the 'Random 1,2,3' Variable

In [69]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [70]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [71]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])