<a href="https://colab.research.google.com/github/Birawin/Data-Science-with-Python-/blob/main/sklearn_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Import the Relevant Data

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
# Load the Data
data = pd.read_csv('1.02.+Multiple+linear+regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
data.describe()

#Rand 1,2,3 - randomly assigns 1, 2, 3

#Sample - The Machine Learning Word for Observations

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [10]:
# Create The Multiple Linear Regression

#Declare the Dependent & Independent Variables
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [11]:
# Regression itself

reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [12]:
#Coefficient
reg.coef_

#Coefficient of SAT and RAND 1,2,3

array([ 0.00165354, -0.00826982])

In [13]:
#Intercept

# y = mx + b (b = intercept, m = coefficent)

reg.intercept_

0.29603261264909486

In [14]:
#Calculating the R-Squared

#R-squared - a universal measure to evaluate how well linear regressions fare and compare...

reg.score(x,y) #Varies depending on the type of regression you're performing


0.4066811952814283

In [15]:
#Adjusted R-Squared Steps on the R-squared and adjusts for the number of variables included in the model

reg.score(x,y)

0.4066811952814283

###**Formula for Adjusted R^2**
$R^2_(adj.) = 1 - (1-R^2)* ((n-1)/(n-p-1))$

In [18]:
x.shape


(84, 2)

In [19]:
n = x.shape[0]
p = x.shape[1]

In [20]:
r2 = reg.score(x,y)

In [21]:
r2 = reg.score(x,y)

In [23]:
adjusted_r2 = 1 - (1-r2)*((n-1)/(n-p-1))
adjusted_r2

0.3920313482513401

#The Adjusted R^2 Value shows that one of the two variables does not increase the explanatory power of the regression. (Since it is less than the R^2 value)
#If we could identify which one and remove it, then we could further simplify our model.
# In order to detect the variables which are unneeded in a model, we will have to execute the 'Feature Selection Process'.


In [25]:
# Feature Selection (Simplifies Model, Improves speeds and prevents a series of unwanted issues arising from having too many features)

In [26]:
#F-regression creates simple linear regressions of each feature & the dependent variable

In [ ]:
#1. GPA <- SAT
#2 GPA <- RAND 1,2,3

#Creates P-values for each regression - p Value is a number, calculated from a statistical test, that describes how likely you are to have found a particular set of observations if the null hypothesis were true.

In [27]:
from sklearn.feature_selection import f_regression

In [29]:
p_values = f_regression(x,y)[1]

In [30]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [33]:
p_values.round()

# SAT - p-value = 0.000
#RAND 1,2,3 - p-value = 1


#Note: These are the univariate p-values reached from simple linear models.
#Tehy do not reflect the interconnection of the features in our multiple linear regression

array([0., 1.])

**#From the calculation above, SAT scores are useful in explaining the regression in our model (P <= 0.005).**

In [42]:
#Creating A Summary Table

reg_summary = pd.DataFrame(data=['SAT', 'Rand 1,2,3'], columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [43]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [44]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676