<a href="https://colab.research.google.com/github/Birawin/Data-Science-with-Python-/blob/main/Tensors%2C_Scalars%2C_Vectors%2C_and_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import the Relevant Libraries**

In [1]:
import numpy as np

**Scalars, Vectors, & Matrices**

In [4]:
s = 5

In [5]:
v = np.array([5,-2,4])

In [3]:
m = np.array([[5,12,6],[-3,0,14]])

**Data Types**

In [6]:
type(s)

int

In [8]:
type(v) #1-dimensional arrays

numpy.ndarray

In [7]:
type(m) #2-dimensional array

numpy.ndarray

In [9]:
s_array = np.array(5)
s_array

array(5)

In [ ]:
type(s_array)

**Data shapes**

In [10]:
m.shape

(2, 3)

In [11]:
v.shape

(3,)

In [12]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [13]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [14]:
#What is a Tensor

m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [15]:
m2 = np.array([[9,8,7],[1,3,-5]])

In [17]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])